<?php
define('ROOTPATH', __DIR__);
define('CONFIGPATH', __DIR__.DIRECTORY_SEPARATOR.'Configuration'.DIRECTORY_SEPARATOR);
define('CACHEPATH', __DIR__.DIRECTORY_SEPARATOR.'Cache'.DIRECTORY_SEPARATOR);
define('POSEIDEN_VER','0.0.2');
